#cloud-config

bootcmd:
  - iptables -I INPUT -p tcp -m tcp --dport 22 -j DROP
  - systemctl mask --now serial-getty@ttyS0.service

runcmd:
  - systemctl daemon-reload
  - systemctl start uid2-operator.service

write_files:
  - path: /etc/systemd/system/uid2-operator.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Start UID 2.0 operator as docker container
      
      [Service]
      Environment="UID2_ENCLAVE_API_TOKEN=dummy"
      Environment="UID2_ENCLAVE_IMAGE_ID=dummy"
      Environment="GHCR_RO_ACCESS_TOKEN="
      Environment="HOME=/run/uid2"
      ExecStartPre=mkdir -p /run/uid2/.config/gcloud
      ExecStartPre=docker login ghcr.io -u gcp-uid2-docker -p ${GHCR_RO_ACCESS_TOKEN}
      ExecStartPre=/usr/bin/docker-credential-gcr configure-docker
      ExecStart=/usr/bin/docker run --rm --name uid2-operator -v /run/uid2/operator.json:/app/conf/config.json -e KUBERNETES_SERVICE_HOST=1 -e core_api_token=${UID2_ENCLAVE_API_TOKEN} -e optout_api_token=${UID2_ENCLAVE_API_TOKEN} -p 80:8080 ghcr.io/iabtechlab/uid2-operator@sha256:${UID2_ENCLAVE_IMAGE_ID}
      ExecStop=/usr/bin/docker stop uid2-operator
      ExecStopPost=/usr/bin/docker rm uid2-operator
  - path: /run/uid2/operator.json
    permissions: 0644
    owner: root
    content: |
      {
        "clients_metadata_path": "https://core-integ.uidapi.com/clients/refresh",
        "keys_metadata_path": "https://core-integ.uidapi.com/key/refresh",
        "keys_acl_metadata_path": "https://core-integ.uidapi.com/key/acl/refresh",
        "salts_metadata_path": "https://core-integ.uidapi.com/salt/refresh",
        "core_attest_url": "https://core-integ.uidapi.com/attest",
        "optout_metadata_path": "https://optout-integ.uidapi.com/optout/refresh",
        "optout_api_uri": "https://optout-integ.uidapi.com/optout/replicate",
        "optout_s3_folder": "optout-v2/",
        "optout_inmem_cache": true,
        "identity_token_expires_after_seconds": 900,
        "refresh_token_expires_after_seconds": 2592000,
        "refresh_identity_token_after_seconds": 300,
        "enclave_platform": "gcp-vmid",
        "enforce_https": true
      }
